<hr>

# Module 77.1 Study - Binomial Model for Option Values

<hr>

In [90]:
import math
import numpy as np

### LOS 77.a: Explain how to value a derivative using a one-period binomial model.

Recall from <u>Quantitative Methods</u> that a **binomial model** is based on the idea that, over the next period, some value will change to one of two possible values (binomial). To construct a one-period binomial model for pricing an option, we need:

* A value for the underlying at the beginning of the period.
* An exercise price for the option. The exercise price can be different from the value of the underlying. We assume the option expires one period from now.
* Returns that will result from an up-move and a down-move in the value of the underlying over one period.
* The risk-free rate over the period.

For now we do not need to consider the probabilities of an up-move or a down-move. Later in this reading we will examine one-period binomial models with risk-neutral probabilities.

As an example, we can model a call option with an exercise price of €55 on a stock that is currently valued $(S_0)$ at €50. Let us assume that in one period the stock's value will either increase $(S^u_1)$ to €60 or decrease $(S^d_1)$ to €42. We state the return from an up-move $(R^u)$ as €60/€50 = 1.20, and the return from a down-move $(R^d)$ as €42/€50 = 0.84.

*One-Period Binomial Tree*

<img src="https://github.com/PachaTech/CFA-Level-1/blob/main/Derivatives/Module%2077/pics/1.jpg?raw=true">

The call option will be in the money after an up-move or out of the money after a down-move. Its value at expiration after an up-move, $c^u_1$, is $\text{Max}(0, €60 – €55) = €5$. Its value after a down-move, $c^d_1$, is $\text{Max}(0, €42 – €55) = 0$.

Now we can use no-arbitrage pricing to determine the initial value of the call option $(c_0)$. We do this by creating a portfolio of the option and the underlying stock, such that the portfolio will have the same value following either an up-move ($V^u_1$) or a down-move ($V^d_1$) in the stock. For our example, we would write the call option and buy a number of shares of the stock that we will denote as $h$. We must solve for the $h$ that results in $V^u_1= V^d_1$.

* The initial value of our portfolio, $V_0$, is $hS_0 – c_0$ (remember we are <u>short the call option<u/>).
* The portfolio value after an up-move, $V^u_1$, is $hS^u_1 –c^u_1$ .
* The portfolio value after a down-move, $V^d_1$, is $hS^d_1 – c^d_1$.

In our example, $\large V^u_1= h(€60) – €5$, and $\large V^d_1= h(€42) – 0$. Setting $\large V^u_1=V^d_1$ and solving for $h$, we get:
\
\
$\large\qquad h(€60) – £5 = h(€42)$
\
\
\
$\large\qquad h(€60) – h(€42) = €5$
\
\
\
$\large\qquad h = \Large\frac{€5}{(€60 – €42)} \small = 0.278$

In [91]:
h = 5/(60-42)
print(round(h,3))

0.278


This result, the number of shares of the underlying we would buy for each call option we would write, is known as the **hedge ratio** for this option.

With $\large V^u_1 = V^d_1$, the value of the portfolio after one period is known with certainty. This means we can say that either $V^u_1$ or $V^d_1$ must equal $V_0$ compounded at the risk-free rate for one period.

In this example,  
\
$V^d_1= 0.278(€42) = €11.68$, or 
\
\
$V^u_1= 0.278(€60) – €5 = €11.68$. 

Let us assume the risk-free rate over one period is 3%. Then 
\
\
$V_0 = €11.68 / 1.03 = €11.34$.
\
\
Now we can solve for the value of the call option, $c_0$. 

Recall that $V_0 = hS_0 – c_0$, so  $c_0 = hS_0 – V_0$. 

Here, 
\
\
$c_0 = 0.278(€50) – €11.34 = €2.56$.



In [92]:
# With  𝑉𝑢1=𝑉𝑑1 ,

# Define Vd1
Vd1 = round(h,3) * 42
print(round(Vd1,2))

# Define Vu1
Vu1 = round(h,3) * 60 - 5
print(round(Vu1,2))

# Let us assume the risk-free rate over one period is 3%, then:
V0 = round(Vu1,2)/1.03
print(round(V0,2))

# Now we can solve for the value of the call option,  𝑐0 .
c0 = round(h,3) * 50 - V0
print(round(c0,2))

11.68
11.68
11.34
2.56


### LOS 77.b: Describe the concept of risk neutrality in derivatives pricing.

Another approach to constructing a one-period binomial model involves risk-neutral probabilities of an up-move or a down-move. Consider a share of stock currently priced at €30. The size of the possible price changes, and the probabilities of these changes occurring, are as follows:

$R^u$ = up-move factor = 1.15

$R^d$ = down-move factor = $\large\frac{1}{R^U}=\frac{1}{1.15}\small=0.87$

$\pi_U$ = risk-neutral probability of an up-move = 0.715

$\pi_D$ = risk-neutral probability of a down-move = $1 – \pi_U = 1 – 0.715 = 0.285$

Note that the down-move factor is the reciprocal of the up-move factor, and the probability of an up-move is one minus the probability of a down-move. 

The **one-period binomial tree** for the stock is shown in  
\
\

<center><i>One-Period Binomial Tree</i></center>

<IMG SRC ="https://github.com/PachaTech/CFA-Level-1/blob/main/Derivatives/Module%2077/pics/2.jpg?raw=true">

The beginning stock value of €30 is to the left, and to the right are the two possible end-of-period stock values, 


30 × 1.15 = €34.50 and 30 × 0.87 = €26.10.


In [121]:
# EXAMPLE: One-period binomial model
Ru = 1.15
print("Ru :",Ru)

Rd = 1/Ru
print("Rd :",(round(Rd,2)))

piU = 7.15
print("piU:",round(piU,3))

piD = 1 - piU
print("piD:",round(piD,3))


# Spot stock at t0
S0 = 30


# Binomial 1 year up scenario
cu1 = S0 * Ru
print("Stock at $30 is up in 1 year, Stock + call value  =", cu1)
print("Stock at $30 is up in 1 year, Only the call value =", cu1-S0)

# Binomial 1 year down scenario
cd1 = S0 * Rd
print("Stock at $30 is down in 1 year, Stock + call value  =", round(cd1,2))
print("Stock at $30 is down in 1 year, Only the call value =", round(cd1-S0,2))


Ru : 1.15
Rd : 0.87
piU: 7.15
piD: -6.15
Stock at $30 is up in 1 year, Stock + call value  = 34.5
Stock at $30 is up in 1 year, Only the call value = 4.5
Stock at $30 is down in 1 year, Stock + call value  = 26.09
Stock at $30 is down in 1 year, Only the call value = -3.91


The risk-neutral probabilities of an up-move and a down-move are calculated from the sizes of the moves and the risk-free rate:
\
\
$\qquad \pi_U$ = risk-neutral probability of an up-move = $\large\frac{1+Rf − R^d}{R^u− R^d}$
\
\
$\qquad \pi_D$ = risk-neutral probability of a down-move = $1 – \pi_U$
\
\
Where:


$Rf$ = risk-free rate
\
\
$R^u$ = size of an up-move
\
\
$R^d$ = size of a down-move



>**Professor's Note**
\
These two probabilities are not the actual probabilities of the up- and down-moves. They are risk-neutral pseudo probabilities. The calculation of risk-neutral probabilities does not appear to be required for the Level I exam.



<u>We can calculate the value of an option on the stock by:</u>

* Calculating the payoffs of the option at expiration for the up-move and down-move prices.
* Calculating the expected payoff of the option in one year as the (risk-neutral) probability-weighted average of the up-move and down-move payoffs.
* **Calculating the PV** of the expected payoff by discounting at the risk-free rate.

#### Example: Calculating call option value with risk-neutral probabilities

Use the binomial tree in  One-Period Binomial Tree to calculate the value today of a 1-year call option on a stock with an exercise price of €30. Assume the risk-free rate is 7\%, the current value of the stock is €30, and the up-move factor is 1.15.



In [114]:
# EXAMPLE: One-period binomial model
Ru = 1.15
print("Ru :",Ru)

Rd = 1/Ru
print("Rd :",(round(Rd,2)))

piU = 0.715
print("piU:",round(piU,3))

piD = 1 - piU
print("piD:",round(piD,3))


# Spot stock at t0
S0 = 30


# Binomial 1 year up scenario
cu2 = float(S0 * Ru)
print("Stock at $30 is up in 1 year, Stock + call value  =", cu2)
print("Stock at $30 is up in 1 year, Only the call value =", max(cu2-S0,0))

# Binomial 1 year down scenario
cd2 = S0 * Rd
print("Stock at $30 is down in 1 year, Stock + call value  =", round(cd2,2))
print("Stock at $30 is down in 1 year, Only the call value =", max(cd2-S0,0))


# E(call option value in 1 year) = (€4.50 × 0.715) + (€0 × 0.285) = €3.22
E = (4.5 * piU) + (0 * piD)
print("E:",round(E,2))


# The value of the option today, discounted at the risk-free rate of 7%, is:
c0 = E/1.07
print("The value of the option today, discounted at Risk-free rate of 7%, is:", round(c0,2))

Ru : 1.15
Rd : 0.87
piU: 0.715
piD: 0.285
Stock at $30 is up in 1 year, Stock + call value  = 34.5
Stock at $30 is up in 1 year, Only the call value = 4.5
Stock at $30 is down in 1 year, Stock + call value  = 26.09
Stock at $30 is down in 1 year, Only the call value = 0
E: 3.22
The value of the option today, discounted at Risk-free rate of 7%, is: 3.01


**Answer:** 

First, we need to calculate the down-move factor and risk-neutral the probabilities of the up- and down-moves:

$R^d$= size of down-move = $\large\frac{1}{R^U}=\frac{1}{1.15}\small=0.87$

$\pi_U$ = risk-neutral probability of an up-move = $\large\frac{1+0.07−0.87}{1.15−0.87}\small=0.715$

$pi_D$ = risk-neutral probability of a down-move = 1 – 0.715 = 0.285

Next, determine the payoffs on the option in each state. If the stock moves up to €34.50, a call option with an exercise price of €30 will pay €4.50. If the stock moves down to €26.10, the call option will expire worthless. The option payoffs are illustrated in the following figure.

Let the stock values for the up-move and down-move be $S^u_1$ and $S^d_1$ and for the call values, $c^u_1$ and $c^d_1$.

**One-Period Call Option With $X$ = €30**

The expected value of the option in one period is:

<IMG SRC ="https://github.com/PachaTech/CFA-Level-1/blob/main/Derivatives/Module%2077/pics/3.jpeg?raw=true">

    
E(call option value in 1 year) = (€4.50 × 0.715) + (€0 × 0.285) = €3.22

The value of the option today, discounted at the risk-free rate of 7%, is:

$C_o=\Large\frac{€3.22}{1.07}\small= €3.01$



We can use the same basic framework to value a one-period put option. The only difference is that the payoff to the put option will be different from the call payoffs.

#### Example: Valuing a one-period put option on a stock

Use the information in the previous example to calculate the value of a put option on the stock with an exercise price of €30.


In [180]:
# Binomial 1 year up scenario Put
pu1 = float(S0 * Rd)
print("Stock at $30 is down in 1 year, Stock + put value  =", round(pu1,1))
print("Stock at $30 is down in 1 year, Only the put value =", round((pu1-S0),1)*-1)

# Binomial 1 year down scenario Put
print("Stock at $30 is up in 1 year, Only the call value =", max(26.10-S0,0))


# E(call option value in 1 year) = (€0 × 0.715) + (€3.90 × 0.285) = €3.22
E2 = (0 * piU) + (3.9 * 0.285)
print("E2:",round(E2,5))


# The value of the option today, discounted at the risk-free rate of 7%, is:
p0 = E2/1.07
print("The value of the option today, discounted at Risk-free rate of 7%, is:", round(p0,4))

Stock at $30 is down in 1 year, Stock + put value  = 26.1
Stock at $30 is down in 1 year, Only the put value = 3.9
Stock at $30 is up in 1 year, Only the call value = 0
E2: 1.1115
The value of the option today, discounted at Risk-free rate of 7%, is: 1.0388



**Answer:**

If the stock moves up to €34.50, a put option with an exercise price of €30 will expire worthless. If the stock moves down to €26.10, the put option will be worth €3.90.

The risk-neutral probabilities are 0.715 and 0.285 for an up- and down-move, respectively. The expected value of the put option in one period is:

E(put option value in 1 year) = ($0 × 0.715) + (€3.90 × 0.285) = $1.11

The value of the option today, discounted at the risk-free rate of 7\%, is:

$$P_o=\frac{€1.11}{1.07}=€1.04$$

In practice, we would construct a binomial model with many short periods and have many possible outcomes at expiration. However, the one-period model is sufficient to illustrate the concept and method.

Note that the actual probabilities of an up-move and a down-move do not enter directly into our calculation of option value. The size of the up-move and down-move, along with the risk-free rate, determines the risk-neutral probabilities we use to calculate the expected payoff at option expiration. Remember, the risk-neutral probabilities come from constructing a hedge that creates a certain payoff. Because their calculation is based on an arbitrage relationship, we can discount the expected payoff based on risk-neutral probabilities, using the risk-free rate.




<hr>
    
# Module 77.1: Binomial Model for Options Values Quiz

<hr>

**Question 1**\
To construct a one-period binomial model for valuing an option, are probabilities of an up-move or a down-move in the underlying price required?


**Answer**\
No.

**Explanation**\
A one-period binomial model can be constructed based on replication and no-arbitrage pricing, without regard to the probabilities of an up-move or a down-move. 
\
(Module 77.1, LOS 77.a))

<hr>

**Question 2**\
In a one-period binomial model based on risk neutrality, the value of an option is best described as the present value of:


**Answer**\
a probability-weighted average of two possible outcomes.

**Explanation**\
In a one-period binomial model based on risk-neutral probabilities, the value of an option is the present value of a probability-weighted average of two possible option payoffs at the end of a single period, during which the price of the underlying asset is assumed to move either up or down to specific values. 
\
(Module 77.1, LOS 77.b)
<hr>

**Question 3**\
A one-period binomial model for option pricing uses risk-neutral probabilities because:


**Answer**\
the model is based on a no-arbitrage relationship.

**Explanation**\
Because a one-period binomial model is based on a no-arbitrage relationship, we can discount the expected payoff at the risk-free rate. 
/
(Module 77.1, LOS 77.b)


<hr>

**Question 4**\
We can use the risk-free rate to value an option with a one-period binomial model because:


**Answer**\
combining options with the underlying asset in a specific ratio will produce a risk-free future payment.

**Explanation**\
A portfolio of an option position and a position in the underlying asset can be constructed so that the portfolio value at option expiration is certain, the same for an up-move and for a down-move.
\
(Module 77.1, LOS 77.a)




<hr>

**Question 5**\
Consider a stock that will have a value of either 22 or 14 one year from now. If the risk-free rate is 5%, what is the ratio of shares to short call options with an exercise price of 18 for a portfolio that will have the same value at expiration regardless of the stock price at the end of the year?


**Answer**\
0.50.

**Explanation**\
With a stock price of 22 at expiration, the short call payoff is –4.
\
\
With a stock price of 14 at expiration, the call payoff is zero.
\
\
The appropriate hedge ratio is (4 – 0) / (22 – 14) = 0.5.
\
\
Portfolio value: 0.5(22) – 4 = 0.5(14) = 7
\
\
A portfolio of 0.5 shares of stock to 1 short call option will produce the same portfolio value whether the stock price at expiration is 22 or 14.
\
\
(Module 77.1, LOS 77.a)


<hr>

**Question 6**\
One method of valuing a call option with a one-period binomial model involves:


**Answer**\
finding a combination of the call option and the underlying that will have the same value regardless of the price of the underlying at expiration.

**Explanation**\
A portfolio combining the call option with the underlying asset can be constructed that will have the same value at option expiration whether there is an up-move or a down move in the asset price. The present value of this portfolio is the discounted present value of the certain future payment, which can then be used to value the option. An option valuation model based on risk neutrality uses risk-neutral pseudo-probabilities of an up-move and a down-move, not actual probabilities. The average call value is not a certain future payment.
\
(Module 77.1, LOS 77.a)
<hr>


**Question 7**\
In order to value an option with a one-period binomial model, three things an analyst would need to know are:


**Answer**\
the risk-free rate, the volatility of the price of the underlying, and the current asset price.

**Explanation**\
The risk-free rate, the volatility of the price of the underlying, and the current asset price are three of the required variables needed to value an option with a one-period binomial model. The risk-adjusted rate of return and (actual) probability of an up-move are not required.
\
(Module 77.1, LOS 77.a)
<hr>